In [ ]:
import numpy as np
import pandas as pd

In [ ]:
df= pd.read_csv("/content/Iris.csv")
df.head()

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,1,5.1,3.5,1.4,0.2,Iris-setosa
1,2,4.9,3.0,1.4,0.2,Iris-setosa
2,3,4.7,3.2,1.3,0.2,Iris-setosa
3,4,4.6,3.1,1.5,0.2,Iris-setosa
4,5,5.0,3.6,1.4,0.2,Iris-setosa


In [ ]:
df.shape

(150, 6)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Id             150 non-null    int64  
 1   SepalLengthCm  150 non-null    float64
 2   SepalWidthCm   150 non-null    float64
 3   PetalLengthCm  150 non-null    float64
 4   PetalWidthCm   150 non-null    float64
 5   Species        150 non-null    object 
dtypes: float64(4), int64(1), object(1)
memory usage: 7.2+ KB


In [ ]:
df.describe()

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm
count,150.000000,150.000000,150.000000,150.000000,150.000000
mean,75.500000,5.843333,3.054000,3.758667,1.198667
std,43.445368,0.828066,0.433594,1.764420,0.763161
min,1.000000,4.300000,2.000000,1.000000,0.100000
25%,38.250000,5.100000,2.800000,1.600000,0.300000
50%,75.500000,5.800000,3.000000,4.350000,1.300000
75%,112.750000,6.400000,3.300000,5.100000,1.800000
max,150.000000,7.900000,4.400000,6.900000,2.500000


In [ ]:
df.isna().sum()  #STEP 1: Eleminate the Null values

,0
Id,0
SepalLengthCm,0
SepalWidthCm,0
PetalLengthCm,0
PetalWidthCm,0
Species,0


###STEP 2 : In Data Preprocessing , Convert Categorical Col to Numerical column

In [ ]:
#To Find Values In Column
df["Species"].value_counts()

,count
Species,
Iris-setosa,50
Iris-versicolor,50
Iris-virginica,50


###1. Manual Conersion

In [ ]:
df1=df.copy(deep=True)
mapping={"Iris-setosa":3, "Iris-versicolor":2 ,"Iris-virginica":1}
df1["Species"]=df1["Species"].map(mapping)
df1.head()

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,1,5.1,3.5,1.4,0.2,3
1,2,4.9,3.0,1.4,0.2,3
2,3,4.7,3.2,1.3,0.2,3
3,4,4.6,3.1,1.5,0.2,3
4,5,5.0,3.6,1.4,0.2,3


In [ ]:
df1.tail()

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
145,146,6.7,3.0,5.2,2.3,1
146,147,6.3,2.5,5.0,1.9,1
147,148,6.5,3.0,5.2,2.0,1
148,149,6.2,3.4,5.4,2.3,1
149,150,5.9,3.0,5.1,1.8,1


###1. label Encoder

In [ ]:
#It is convert each value in a column to number
df2=df.copy(deep=True)
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
df2["Species"]=le.fit_transform(df2["Species"])
df2.head()

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,1,5.1,3.5,1.4,0.2,0
1,2,4.9,3.0,1.4,0.2,0
2,3,4.7,3.2,1.3,0.2,0
3,4,4.6,3.1,1.5,0.2,0
4,5,5.0,3.6,1.4,0.2,0


In [ ]:
df2["Species"]=le.inverse_transform(df2["Species"])
df2.head()

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,1,5.1,3.5,1.4,0.2,Iris-setosa
1,2,4.9,3.0,1.4,0.2,Iris-setosa
2,3,4.7,3.2,1.3,0.2,Iris-setosa
3,4,4.6,3.1,1.5,0.2,Iris-setosa
4,5,5.0,3.6,1.4,0.2,Iris-setosa


###2. One Hot Encoding

In [ ]:
df3=df.copy(deep=True)
from sklearn.preprocessing import OneHotEncoder
ohe=OneHotEncoder()
x3=df3[["Species"]]    #[] use for multiple columns
ohe.fit_transform(x3).toarray()

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0

###4. Dummy Variables

In [ ]:
# This is Same as OneCodeEncoding But it comes with column names
pd.get_dummies(df3["Species"])

,Iris-setosa,Iris-versicolor,Iris-virginica
0,True,False,False
1,True,False,False
2,True,False,False
3,True,False,False
4,True,False,False
...,...,...,...
145,False,False,True
146,False,False,True
147,False,False,True
148,False,False,True


##Feature Scaling
##1. Min Max Scaler

In [ ]:
from sklearn.preprocessing import MinMaxScaler
df4=df.copy(deep=True)
x2=df4.iloc[:,0:5]  #iloc=integer location  # row,column
mms=MinMaxScaler(feature_range=(1,2))  # x_Scaled = (x-x_min)/(x_max-x_min)
x2_Scaled=mms.fit_transform(x2)
x2_Scaled

array([[1.        , 1.22222222, 1.625     , 1.06779661, 1.04166667],
       [1.00671141, 1.16666667, 1.41666667, 1.06779661, 1.04166667],
       [1.01342282, 1.11111111, 1.5       , 1.05084746, 1.04166667],
       [1.02013423, 1.08333333, 1.45833333, 1.08474576, 1.04166667],
       [1.02684564, 1.19444444, 1.66666667, 1.06779661, 1.04166667],
       [1.03355705, 1.30555556, 1.79166667, 1.11864407, 1.125     ],
       [1.04026846, 1.08333333, 1.58333333, 1.06779661, 1.08333333],
       [1.04697987, 1.19444444, 1.58333333, 1.08474576, 1.04166667],
       [1.05369128, 1.02777778, 1.375     , 1.06779661, 1.04166667],
       [1.06040268, 1.16666667, 1.45833333, 1.08474576, 1.        ],
       [1.06711409, 1.30555556, 1.70833333, 1.08474576, 1.04166667],
       [1.0738255 , 1.13888889, 1.58333333, 1.10169492, 1.04166667],
       [1.08053691, 1.13888889, 1.41666667, 1.06779661, 1.        ],
       [1.08724832, 1.        , 1.41666667, 1.01694915, 1.        ],
       [1.09395973, 1.41666667, 1.

###2. Standard Scaler

In [ ]:
from sklearn.preprocessing import StandardScaler
df5=df.copy(deep=True)
x5=df5.iloc[:,0:5]
scaler=StandardScaler()
x5_Scaled=scaler.fit_transform(x5)
x5_Scaled

array([[-1.72054204e+00, -9.00681170e-01,  1.03205722e+00,
        -1.34127240e+00, -1.31297673e+00],
       [-1.69744751e+00, -1.14301691e+00, -1.24957601e-01,
        -1.34127240e+00, -1.31297673e+00],
       [-1.67435299e+00, -1.38535265e+00,  3.37848329e-01,
        -1.39813811e+00, -1.31297673e+00],
       [-1.65125846e+00, -1.50652052e+00,  1.06445364e-01,
        -1.28440670e+00, -1.31297673e+00],
       [-1.62816394e+00, -1.02184904e+00,  1.26346019e+00,
        -1.34127240e+00, -1.31297673e+00],
       [-1.60506942e+00, -5.37177559e-01,  1.95766909e+00,
        -1.17067529e+00, -1.05003079e+00],
       [-1.58197489e+00, -1.50652052e+00,  8.00654259e-01,
        -1.34127240e+00, -1.18150376e+00],
       [-1.55888037e+00, -1.02184904e+00,  8.00654259e-01,
        -1.28440670e+00, -1.31297673e+00],
       [-1.53578584e+00, -1.74885626e+00, -3.56360566e-01,
        -1.34127240e+00, -1.31297673e+00],
       [-1.51269132e+00, -1.14301691e+00,  1.06445364e-01,
        -1.28440670e+00

###3. Binarizer

In [ ]:
from sklearn.preprocessing import Binarizer
df6=df.copy(deep=True)
x6=df6.iloc[:,0:5]
bin=Binarizer(threshold=4)  # if the value is less than threshold value displays 0 else dispalys 1
x6_scaled=bin.fit_transform(x6)
x6_scaled

array([[0., 1., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [1., 1., 0., 0., 0.],
       [1., 1., 0., 0., 0.],
       [1., 1., 0., 0., 0.],
       [1., 1., 0., 0., 0.],
       [1., 1., 0., 0., 0.],
       [1., 1., 0., 0., 0.],
       [1., 1., 0., 0., 0.],
       [1., 1., 0., 0., 0.],
       [1., 1., 0., 0., 0.],
       [1., 1., 0., 0., 0.],
       [1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0.],
       [1., 1., 0., 0., 0.],
       [1., 1., 0., 0., 0.],
       [1., 1., 0., 0., 0.],
       [1., 1., 0., 0., 0.],
       [1., 1., 0., 0., 0.],
       [1., 1., 0., 0., 0.],
       [1., 1., 0., 0., 0.],
       [1., 1., 0., 0., 0.],
       [1., 1., 0., 0., 0.],
       [1., 1., 0., 0., 0.],
       [1., 1., 0., 0., 0.],
       [1., 1., 0., 0., 0.],
       [1., 1., 0., 0., 0.],
       [1., 1., 0., 0., 0.],
       [1., 1., 0., 0., 0.],
       [1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0.],
       [1., 1., 1., 0., 0.],
       [1., 1.