##importing the Libraries

In [ ]:
import pandas as pd
import numpy as np

##Reading the Datasrt

In [ ]:
df=pd.read_csv("/content/Housing.csv")
df.head()

,Unnamed: 0,price,lotsize,bedrooms,bathrms,stories,driveway,recroom,fullbase,gashw,airco,garagepl,prefarea
0,1,42000.0,5850,3,1,2,yes,no,yes,no,no,1,no
1,2,38500.0,4000,2,1,1,yes,no,no,no,no,0,no
2,3,49500.0,3060,3,1,1,yes,no,no,no,no,0,no
3,4,60500.0,6650,3,1,2,yes,yes,no,no,no,0,no
4,5,61000.0,6360,2,1,1,yes,no,no,no,no,0,no


### Checking for all the variable types

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 546 entries, 0 to 545
Data columns (total 13 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   Unnamed: 0  546 non-null    int64  
 1   price       546 non-null    float64
 2   lotsize     546 non-null    int64  
 3   bedrooms    546 non-null    int64  
 4   bathrms     546 non-null    int64  
 5   stories     546 non-null    int64  
 6   driveway    546 non-null    object 
 7   recroom     546 non-null    object 
 8   fullbase    546 non-null    object 
 9   gashw       546 non-null    object 
 10  airco       546 non-null    object 
 11  garagepl    546 non-null    int64  
 12  prefarea    546 non-null    object 
dtypes: float64(1), int64(6), object(6)
memory usage: 55.6+ KB


In [ ]:
df.shape

(546, 13)

In [ ]:
df.describe()

,Unnamed: 0,price,lotsize,bedrooms,bathrms,stories,garagepl
count,546.000000,546.000000,546.000000,546.000000,546.000000,546.000000,546.000000
mean,273.500000,68121.597070,5150.265568,2.965201,1.285714,1.807692,0.692308
std,157.760895,26702.670926,2168.158725,0.737388,0.502158,0.868203,0.861307
min,1.000000,25000.000000,1650.000000,1.000000,1.000000,1.000000,0.000000
25%,137.250000,49125.000000,3600.000000,2.000000,1.000000,1.000000,0.000000
50%,273.500000,62000.000000,4600.000000,3.000000,1.000000,2.000000,0.000000
75%,409.750000,82000.000000,6360.000000,3.000000,2.000000,2.000000,1.000000
max,546.000000,190000.000000,16200.000000,6.000000,4.000000,4.000000,3.000000


### Check Null Values

In [ ]:
df.isna().sum()

,0
Unnamed: 0,0
price,0
lotsize,0
bedrooms,0
bathrms,0
stories,0
driveway,0
recroom,0
fullbase,0
gashw,0


###Label Encoder

In [ ]:
#Convert text to 0 & 1 [Binary form]
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
col=["driveway"	, "recroom"	, "fullbase"	, "gashw"	, "airco" , "prefarea"]
for f in col:
  df[f]=le.fit_transform(df[f])
df.head()

,Unnamed: 0,price,lotsize,bedrooms,bathrms,stories,driveway,recroom,fullbase,gashw,airco,garagepl,prefarea
0,1,42000.0,5850,3,1,2,1,0,1,0,0,1,0
1,2,38500.0,4000,2,1,1,1,0,0,0,0,0,0
2,3,49500.0,3060,3,1,1,1,0,0,0,0,0,0
3,4,60500.0,6650,3,1,2,1,1,0,0,0,0,0
4,5,61000.0,6360,2,1,1,1,0,0,0,0,0,0


###Determing X & Y for SLR

In [ ]:
df.corr()
# Correlation quantifies the strength of the linear relationship b/w a pair of var
# Correlation of r=0.9 suggest a strong, positive association b/w 2 var
# Correlation of r=-0.2 suggest a weak, negative association.

,Unnamed: 0,price,lotsize,bedrooms,bathrms,stories,driveway,recroom,fullbase,gashw,airco,garagepl,prefarea
Unnamed: 0,1.000000,0.376007,0.374338,0.114219,0.108395,0.231427,0.314014,0.096721,-0.002034,-0.033494,0.157111,0.125326,0.519994
price,0.376007,1.000000,0.535796,0.366447,0.516719,0.421190,0.297167,0.254960,0.186218,0.092837,0.453347,0.383302,0.329074
lotsize,0.374338,0.535796,1.000000,0.151851,0.193833,0.083675,0.288778,0.140327,0.047487,-0.009201,0.221765,0.352872,0.234782
bedrooms,0.114219,0.366447,0.151851,1.000000,0.373769,0.407974,-0.011996,0.080492,0.097201,0.046028,0.160412,0.139117,0.078953
bathrms,0.108395,0.516719,0.193833,0.373769,1.000000,0.324066,0.041955,0.126892,0.102791,0.067365,0.184955,0.178178,0.064013
stories,0.231427,0.421190,0.083675,0.407974,0.324066,1.000000,0.122499,0.042281,-0.173860,0.018261,0.296216,0.043412,0.042940
driveway,0.314014,0.297167,0.288778,-0.011996,0.041955,0.122499,1.000000,0.091959,0.043428,-0.011942,0.106290,0.203682,0.199378
recroom,0.096721,0.254960,0.140327,0.080492,0.126892,0.042281,0.091959,1.000000,0.372434,-0.010119,0.136626,0.038122,0.161292
fullbase,-0.002034,0.186218,0.047487,0.097201,0.102791,-0.173860,0.043428,0.372434,1.000000,0.004677,0.045248,0.052524,0.228651
gashw,-0.033494,0.092837,-0.009201,0.046028,0.067365,0.018261,-0.011942,-0.010119,0.004677,1.000000,-0.130350,0.068144,-0.059170


##Defining what is X & Y for model
###Declaration & Inatialization

In [ ]:
x = df[["lotsize"]]
y = df[["price"]]
# Double brackets are used when we want to select 1 or more columns as a dataframe
# Single brackets are used when we want select single column

###Dividing into Train & Test Data

In [ ]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2, random_state=2)

###Building simple Linear Regression Model

In [ ]:
from sklearn.linear_model import LinearRegression
slr = LinearRegression()
slr.fit(x_train,y_train)

LinearRegression()

In [ ]:
slr.coef_  # The slope is often called the reggresion coefficient

array([[6.24921517]])

In [ ]:
slr.intercept_  # Constant value

array([35175.11123177])

###Evaluation

In [ ]:
ypredict = slr.predict(x_test)
ypredict

array([[ 78919.61739631],
       [ 58797.14456062],
       [ 57172.34861737],
       [ 76794.88423975],
       [ 72670.40222995],
       [ 77357.31360472],
       [ 65421.31263697],
       [ 71108.09843836],
       [ 68420.93591682],
       [ 76419.93132976],
       [ 63296.5794804 ],
       [ 53922.75673086],
       [ 77669.77436304],
       [ 81569.28462685],
       [ 57797.270134  ],
       [ 51735.53142263],
       [ 55047.6154608 ],
       [ 49392.07573524],
       [ 72670.40222995],
       [ 72670.40222995],
       [ 52672.91369759],
       [110728.1225931 ],
       [ 58047.23874066],
       [ 51485.56281598],
       [ 68295.95161349],
       [ 75795.00981313],
       [ 57172.34861737],
       [ 74920.11968984],
       [ 79888.2457471 ],
       [ 52341.70529377],
       [ 82669.14649613],
       [ 72670.40222995],
       [ 76513.66955726],
       [ 48767.15421861],
       [ 53922.75673086],
       [ 69545.79464676],
       [ 75170.08829649],
       [ 72670.40222995],
       [ 571

In [ ]:
#Accuracy Score
from sklearn.metrics import r2_score
r2_score(y_test,ypredict)

0.278833792041032

### Prediction for House price for given lotsize

In [ ]:
import numpy as np
x_new = np.array([5000]).reshape(1,-1)
slr.predict(x_new)

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([[66421.18706358]])

##Multiple Linear Regression

In [ ]:
#Multiple Linear Regression = for 1 'y' variable to take more than 1 'x' variable
#Single Linear Regression  = for 1 'y' variable take 1 'x' variable


###prediction of lotsize & bathrooms

In [ ]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score
#select the features & target var
x=df[["lotsize","bathrms"]]
y=df.price
#Split data into training & testing sets
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=2)
#create linear refression model & fit to the training Data
mlr=LinearRegression()
mlr.fit(x_train,y_train)

print(mlr.coef_)
print(mlr.intercept_)

ypredict=mlr.predict(x_test)
r2=r2_score(y_test,ypredict)
print("r2_score:" , r2)
#Deploy
xnew = np.array([[5000,2]])
prediction = mlr.predict(xnew)
print("prediction:",prediction)

[5.36871349e+00 2.08354008e+04]
13296.788853511454
r2_score: 0.5434071368245021
prediction: [81811.15796081]


/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
